import Foundation

class Liveness3DStrings {
    static var values = ["FaceTec_accessibility_cancel_button":"Cancelar2",
                         "FaceTec_accessibility_torch_button":"Ligar flash",
                         "FaceTec_action_ok":"OK",
                         "FaceTec_action_im_ready":"Começar2",
                         "FaceTec_action_try_again":"Tentar novamente",
                         "FaceTec_action_continue":"Continuar2",
                         "FaceTec_action_take_photo":"Tirar Foto",
                         "FaceTec_action_accept_photo":"Aceitar",
                         "FaceTec_action_confirm":"Confiramção das informações",
                         "FaceTec_camera_permission_header":"Habilite a Camera",
                         "FaceTec_feedback_center_face":"Centralize seu rosto",
                         "FaceTec_feedback_face_not_found":"Enquadre o Seu Rosto",
                         "FaceTec_feedback_face_not_looking_straight_ahead":"Olhe Para Frente",
                         "FaceTec_feedback_face_not_upright":"Mantenha a Cabeça Reta",
                         "FaceTec_feedback_hold_steady":"Segure Firme",
                         "FaceTec_feedback_move_phone_away":"2Afaste-se2",
                         "FaceTec_feedback_move_phone_closer":"2Aproxime-se2",
                         "FaceTec_feedback_move_phone_to_eye_level":"Telefone ao Nível dos Olhos",
                         "FaceTec_feedback_use_even_lighting":"Ilumine Seu Rosto Uniformemente",
                         "FaceTec_idscan_type_selection_header":"Prepare to Scan\nYour ID Document",
                         "FaceTec_instructions_header_ready_1":"Prepare-se para seu",
                         "FaceTec_instructions_header_ready_2":"reconhecimento facial.",
                         "FaceTec_instructions_message_ready_1":"Enquadre seu rosto na moldura,",
                         "FaceTec_instructions_message_ready_2":"aproxime-se e toque em começar.",
                         "FaceTec_presession_frame_your_face":"Encaixe Seu Rosto no Espaço Oval",
                         "FaceTec_presession_position_face_straight_in_oval":"Olhe Para Frente",
                         "FaceTec_presession_hold_steady_3":"Aguente Firme: 3",
                         "FaceTec_presession_hold_steady_2":"Aguente Firme: 2",
                         "FaceTec_presession_hold_steady_1":"Aguente Firme: 1",
                         "FaceTec_presession_eyes_straight_ahead":"Olhe Para Frente",
                         "FaceTec_presession_remove_dark_glasses":"Tire Seus Óculos de Sol",
                         "FaceTec_presession_neutral_expression":"Fique Neutro, Não Sorria",
                         "FaceTec_presession_conditions_too_bright":"Ambiente Muito Iluminado",
                         "FaceTec_presession_brighten_your_environment":"Ambiente Muito Escuro",
                         "FaceTec_result_facescan_upload_message":"",
                         "FaceTec_result_success_message":"Tudo certo!",
                         "FaceTec_result_idscan_unsuccess_message":"Não foi possível concluir sua verificação.",
                         "FaceTec_retry_header":"Vamos tentar novamente?",
                         "FaceTec_retry_subheader_message":"Siga o exemplo de foto ideal abaixo:",
                         "FaceTec_retry_instruction_message_1":"Expressão Neutra, Sem Sorrir",
                         "FaceTec_retry_instruction_message_2":"Evite reflexos e iluminação extrema.",
                         "FaceTec_retry_instruction_message_3":"Muito Borrado, Limpe Sua Câmera",
                         "FaceTec_retry_your_image_label":"Sua foto",
                         "FaceTec_retry_ideal_image_label":"Foto ideal"];
}
